INSERT INTO SQLD.TB_CERTI T (T.CERTI_CD, T.CERTI_NM, T.ISSUE_INSTI_NM) VALUES ('100021', 'SQLD합격패스', '패스트캠퍼스'); 

COMMIT; 

SELECT *
 FROM SQLD.TB_CERTI  A
WHERE A.CERTI_CD = '100021'
;

UPDATE SQLD.TB_CERTI  A
  SET A.ISSUE_INSTI_NM = '패스트캠퍼스온라인'
WHERE A.CERTI_CD = '100021'
;

COMMIT;


SELECT *
 FROM SQLD.TB_CERTI  A
WHERE A.CERTI_CD = '100021'
;

DELETE FROM SQLD.TB_CERTI  A
WHERE A.CERTI_CD = '100021'
;

COMMIT;

SELECT *
 FROM SQLD.TB_CERTI  A
WHERE A.CERTI_CD = '100021'
;


select 출력하고싶은칼럼명
select distinct 