
SELECT A.EMP_NO
      , A.EMP_NM
      , A.SEX_CD
      , A.BIRTH_DE
      , A.DEPT_CD
      , A.ADDR 
   FROM TB_EMP A
   WHERE A.EMP_NM LIKE '박__'
   ;



SELECT A.EMP_NO
      , A.EMP_NM
      , A.SEX_CD
      , A.BIRTH_DE
      , A.DEPT_CD
      , A.ADDR 
      , NVL(A.DIRECT_MANAGER_EMP_NO, '상사없음') DIRECT_MANAGER_EMP_NO
   FROM TB_EMP A
   WHERE A.DIRECT_MANAGER_EMP_NO IS NULL -- NULL은 '='로 비교할 수 없음 
   ; 

 SELECT A.EMP_NO
      , A.EMP_NM
      , A.SEX_CD
      , A.BIRTH_DE
      , A.DEPT_CD
      , A.ADDR 
   FROM TB_EMP A
  WHERE A.BIRTH_DE BETWEEN '19900101' AND '19991231'
    AND A.DEPT_CD IN ('100004', '100006')  --디자인팀, 데이터팀
    AND NOT (   A.ADDR LIKE '%수원시%' --"수원시"에 사는 사람
             OR A.ADDR LIKE '%성남시%' --"성남시"에 사는 사람
            )


DROP TABLE SQLD.CHAR_COMPARE;

CREATE TABLE SQLD.CHAR_COMPARE
(
  SN CHAR(10)
, CHAR_COMPARE_4 CHAR(4)
, CHAR_COMPARE_6 CHAR(6) 
)
;

INSERT INTO SQLD.CHAR_COMPARE VALUES ('1000000001', 'SQLD', 'SQLD');
INSERT INTO SQLD.CHAR_COMPARE VALUES ('1000000002', 'SQLD', 'SQLA');
COMMIT; 



SELECT 
       REPLACE(CHAR_COMPARE_4, ' ', '_') AS CHAR_COMPARE_4
     , REPLACE(CHAR_COMPARE_6, ' ', '_') AS CHAR_COMPARE_6
  FROM SQLD.CHAR_COMPARE
;


SELECT 
       REPLACE(CHAR_COMPARE_4, ' ', '_') AS CHAR_COMPARE_4
     , REPLACE(CHAR_COMPARE_6, ' ', '_') AS CHAR_COMPARE_6
  FROM SQLD.CHAR_COMPARE
 WHERE SN = '1000000001'
   AND CHAR_COMPARE_4 = CHAR_COMPARE_6
;


SELECT 
       REPLACE(CHAR_COMPARE_4, ' ', '_') AS CHAR_COMPARE_4
     , REPLACE(CHAR_COMPARE_6, ' ', '_') AS CHAR_COMPARE_6
  FROM SQLD.CHAR_COMPARE
 WHERE SN = '1000000002'
   AND CHAR_COMPARE_4 > CHAR_COMPARE_6 --알파벳D가 더 큼 
;
